### ISSUE TITLE
Link to ZIP doesn't work in quick start guide

### ISSUE THREAD

**Issue by pipacs** [microsoftgraph/msgraph-training-ios-swift#8]
When clicking on "Download our sample" in https://developer.microsoft.com/en-us/graph/quick-start?appID=my_app_id, it opens https://codeload.github.com/microsoftgraph/msgraph-training-ios-swift/zip/master which is a 404.

**Comment by jasonjoh** [comment]
Thanks - it's a known issue with all those zips in Safari. Are you using Safari?

**Comment by pipacs** [comment]
Yes, I’m on a Mac.

**Comment by jasonjoh** [comment]
Thanks for confirming. This is a known issue with the Graph site unfortunately, but it is being worked on. For now you can get the code from this repository.
